### PR TITLE
Enable itemData prop

### PR DESCRIPTION
**Pull request by SpadarShut**
Passes itemData prop to item rendering function.

This is a PR with the code from @akraines , https://github.com/akraines/react-window-dynamic-list/commit/c0ee642bbd3de6ca7bd44ed60cb905ac57204579

### CODE REVIEW

**Review by gnir-work — APPROVED** [review]
Thanks for the awesome PR :)

**Comment by gnir-work** [comment]
Hey,
After merging your PR I noticed a small bug.
VariableSizeList passes the whole itemData prop to its children while you
pass the current index to the measureIndex component childrens.
This resulted in incorrect measurements which led to overlapping elements :(
The fix is located in this commit -
https://github.com/gnir-work/react-window-dynamic-list/commit/223e3ad2c779f1fc1cc1cdd6647e499f116cf289
Any way you can receive this feature at ***@***.***

And again, Thanks for the contribution to the project! :D

**Comment by SpadarShut** [comment]
Thanks, I didn't actually test the code, just submitted someone else's, because I needed this feature in my project. 
Totally agree all of the itemData should be passed.

And thanks for maintaining this project!

**Comment by gnir-work** [comment]
No problem :)
In case you have any other requirements while developing the project I
would love to hear and help if possible.

**Pull request merged**
